name: flutter_ui_challenges
description: Trying to replicate various app UIs in flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 3.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.4
  flutter_custom_clippers: ^0.1.1
  intro_views_flutter:
  wave:
  font_awesome_flutter: ^8.4.0
  url_launcher: ^5.0.2
  shared_preferences: ^0.5.3
  bottomreveal: ^1.0.0
  charts_flutter: ^0.6.0
  animated_floatactionbuttons: ^0.1.0
  share: ^0.6.2
  intl: ^0.15.8
  flare_flutter: 1.5.9
  firebase_auth: ^0.14.0+5
  provider: ^3.1.0
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.12.9+4
  cached_network_image: ^1.1.1
  package_info: ^0.4.0+6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_automation:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/app-store-logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/smwallet/
    - assets/hotel/
    - assets/icon/
    - assets/flare/
    - lib/src/pages/animations/
    - lib/src/pages/animations/animation1/
    - lib/src/pages/blog/
    - lib/src/pages/dialogs/
    - lib/src/pages/ecommerce/
    - lib/src/pages/food/
    - lib/src/pages/grocery/
    - lib/src/pages/hotel/
    - lib/src/pages/login/
    - lib/src/pages/lists/
    - lib/src/pages/misc/
    - lib/src/pages/navigation/
    - lib/src/pages/onboarding/
    - lib/src/pages/profile/
    - lib/src/pages/quiz_app/
    - lib/src/pages/todo/
    - lib/src/pages/travel/
    - lib/src/pages/invitation/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
