name: flutter_ui_challenges
description: Trying to replicate various app UIs in flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 3.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: ^0.1.0
  animator: ^3.2.0
  bottomreveal: ^2.0.0
  cached_network_image: ^3.2.3
  charts_flutter: ^0.12.0
  crop: ^0.5.3
  flare_flutter: ^3.0.2
  flutter_custom_clippers: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  flutter_speed_dial: ^3.0.5
  share_plus: ^6.3.0
  simple_animations: ^5.0.0+3
  url_launcher: ^6.1.7
  string_scanner: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation: null
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/app-store-logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/smwallet/
    - assets/discoveryimages/
    - assets/hotel/
    - assets/icon/
    - assets/fooditem/
    - assets/flare/
    - lib/src/pages/animations/
    - lib/src/pages/animations/animation1/
    - lib/src/pages/bike/
    - lib/src/pages/blog/
    - lib/src/pages/dialogs/
    - lib/src/pages/dashboard/
    - lib/src/pages/ecommerce/
    - lib/src/pages/food/
    - lib/src/pages/grocery/
    - lib/src/pages/hotel/
    - lib/src/pages/login/
    - lib/src/pages/lists/
    - lib/src/pages/misc/
    - lib/src/pages/navigation/
    - lib/src/pages/onboarding/
    - lib/src/pages/profile/
    - lib/src/pages/quotes/
    - lib/src/pages/quiz_app/
    - lib/src/pages/todo/
    - lib/src/pages/settings/
    - lib/src/pages/travel/
    - lib/src/pages/invitation/
    - lib/src/nic_asia_clone/
    - lib/src/furniture_app/
    - assets/nicasiaassets/
    - lib/src/khalti_clone/
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
